# Generated by Django 5.2.10 on 2026-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='expense_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fixed/Essential', 'Fixed/Essential'), ('Food & Daily Living', 'Food & Daily Living'), ('Transportation', 'Transportation'), ('Personal & Lifestyle', 'Personal & Lifestyle'), ('Health & Wellness', 'Health & Wellness'), ('Education', 'Education'), ('Entertainment & Social', 'Entertainment & Social'), ('Work/Business', 'Work/Business'), ('Giving & Miscellaneous', 'Giving & Miscellaneous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
