# Generated by Django 5.2.10 on 2026-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_alter_expense_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_created', '-date']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fixed/Essential', '🏠 Fixed/Essential'), ('Food & Daily Living', '🍽️ Food & Daily Living'), ('Transportation', '🚗 Transportation'), ('Personal & Lifestyle', '🧍 Personal & Lifestyle'), ('Health & Wellness', '🏥 Health & Wellness'), ('Education', '🎓 Education'), ('Entertainment & Social', '🎉 Entertainment & Social'), ('Work/Business', '💼 Work/Business'), ('Giving & Miscellaneous', '🎁 Giving & Miscellaneous')], max_length=100),
        ),
    ]
